"""first

Revision ID: 211899668d12
Revises: 
Create Date: 2022-06-21 02:55:56.962567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211899668d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encrypted_text', sa.String(), nullable=False),
    sa.Column('decrypted_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encryption_encrypted_text'), 'encryption', ['encrypted_text'], unique=True)
    op.create_index(op.f('ix_encryption_id'), 'encryption', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encryption_id'), table_name='encryption')
    op.drop_index(op.f('ix_encryption_encrypted_text'), table_name='encryption')
    op.drop_table('encryption')
    # ### end Alembic commands ###
